### ISSUE TITLE
How can we use Custom Splash Screen with this template ?

### ISSUE THREAD

**Issue by dnxit** [kbfoot/UWPNavBasics#2]
How can we use Custom Splash Screen with this template ?

**Comment by pipgirl** [comment]
Hi Muhammad,

You will need to include your custom image in the Assets folder. Then open Package.appxmanifest, it should display in a GUI. Go to the Visual Assets tab. There you can customize your images, including the Splash Screen.

Thanks!

**Comment by dnxit** [comment]
I know about that that's the default splash I need custom I need to provide an Image for the whole view able area but in the default I can only provide images which will be displayed in the center only
